services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
      - dbdata:/app/db
      - ./ssl:/ssl
    env_file:
      - .env
    depends_on:
      - face_engine

  face_engine:
    build:
      context: .
      dockerfile: face_engine/Dockerfile
    container_name: face_engine
    ports:
      - "8000:8000"
    volumes:
      - ./face_engine:/app
      - dbdata:/app/db
      - ./ssl:/ssl
    env_file:
      - .env

volumes:
  dbdata:
